// Sinrad — preload bridge (safe API surface for the renderer & the pet window)
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("electronAPI", {
  // window controls
  winMin:   () => ipcRenderer.send("win-min"),
  winMax:   () => ipcRenderer.send("win-max"),
  winClose: () => ipcRenderer.send("win-close"),

  // boot splash (video plays first, then the app opens)
  bootDone: () => ipcRenderer.send("boot-done"),

  // open things with the OS
  shellOpen: (url) => ipcRenderer.send("shell-open", url),
  openPath:  (p)   => ipcRenderer.invoke("open-path", p),

  // persistent on-disk store
  storeLoad: () => ipcRenderer.invoke("store-load"),
  storeSecurity: () => ipcRenderer.invoke("store-security"),
  storeSave: (data) => ipcRenderer.invoke("store-save", data),
  ideaImagesPick: () => ipcRenderer.invoke("idea-images-pick"),
  ideaImagesImport: (items) => ipcRenderer.invoke("idea-images-import", items),
  ideaImageCopy: (name) => ipcRenderer.invoke("idea-image-copy", name),
  linkCheck: (url) => ipcRenderer.invoke("link-check", url),
  sitePreview: (url, mode) => ipcRenderer.invoke("site-preview", url, mode || "rich"),
  folderPreview: (folder) => ipcRenderer.invoke("folder-preview", folder),
  backupExport: (data, password) => ipcRenderer.invoke("backup-export", data, password),
  backupImport: (password) => ipcRenderer.invoke("backup-import", password),

  // desktop pet (floating Norma that lives OUTSIDE the app window)
  petShow: () => ipcRenderer.send("pet-show"),
  petHide: () => ipcRenderer.send("pet-hide"),
  petDragStart: (off) => ipcRenderer.send("pet-drag-start", off),
  petDragEnd:   () => ipcRenderer.send("pet-drag-end"),
  setMouseIgnore: (b, opts) => ipcRenderer.send("set-mouse-ignore", b, opts),
  petNav: (mod) => ipcRenderer.send("pet-nav", mod),
  petPin: () => ipcRenderer.send("pet-pin"),

  // main window <- pet / main process
  onNormaDock: (cb) => ipcRenderer.on("norma-dock", () => cb()),
  onNormaNav:  (cb) => ipcRenderer.on("norma-nav", (_, m) => cb(m)),
  fsScan: (o) => ipcRenderer.send("fs-scan", o),
  fsScanCancel: (o) => ipcRenderer.send("fs-scan-cancel", o),
  onFsChunk: (cb) => ipcRenderer.on("fs-scan-chunk", (_, p) => cb(p)),
  onFsDone: (cb) => ipcRenderer.on("fs-scan-done", (_, p) => cb(p)),
  fsHome: () => ipcRenderer.invoke("fs-home"),
  appVersion: () => ipcRenderer.invoke("app-version"),
  updateCheck: (v) => ipcRenderer.invoke("update-check", v),
  updateDownload: (o) => ipcRenderer.invoke("update-download", o),
  updateInstall: (t) => ipcRenderer.invoke("update-install", t),
  onUpdateProgress: (cb) => ipcRenderer.on("update-progress", (_, p) => cb(p)),
  clipRead: () => ipcRenderer.invoke("clip-read"),
  clipClearIf: (value) => ipcRenderer.invoke("clip-clear-if", value),
  onHotkeyPark: (cb) => ipcRenderer.on("hotkey-park", (_, t) => cb(t)),
  hotkeyStatus: (cb) => ipcRenderer.on("hotkey-status", (_, mm) => cb(mm)),
  hotkeyToggle: (enabled) => ipcRenderer.invoke("hotkey-toggle", enabled),
  hotkeysUpdate: (hotkeys) => ipcRenderer.invoke("hotkeys-update", hotkeys),
  hotkeyCapture: (active) => ipcRenderer.send("hotkey-capture", !!active),
  onProtocolPark: (cb) => ipcRenderer.on("protocol-park", (_, data) => cb(data)),
  protocolParkAck: (requestId, ok) => ipcRenderer.send("protocol-park-ack", requestId, !!ok),
  setAutostart: (enabled) => ipcRenderer.invoke("set-autostart", enabled),
  extDir: () => ipcRenderer.invoke("ext-dir"),
  extOpen: () => ipcRenderer.invoke("ext-open"),
  mediaAssets: () => ipcRenderer.invoke("media-assets"),
  mediaOpen: (kind) => ipcRenderer.invoke("media-open", kind),
  showNotif: (data) => ipcRenderer.send("show-notif", data),
  dataPath: (cb) => ipcRenderer.on("data-path", (_, pp) => cb(pp)),

  // pet recent / pinned folders
  syncPetRecents: (slots) => ipcRenderer.send("sync-pet-recents", slots),
  petRecents: () => ipcRenderer.invoke("pet-recents"),
  onRecentFolders: (cb) => ipcRenderer.on("recent-folders-update", (_, list) => cb(list)),
  onRecordRecentFolder: (cb) => ipcRenderer.on("record-recent-folder", (_, info) => cb(info)),
  onAppFocus: (cb) => ipcRenderer.on("app-focus", () => cb()),
  onCommandPalette: (cb) => ipcRenderer.on("command-palette", () => cb()),

  // unified offline reader
  offlineLoad: () => ipcRenderer.invoke("offline-load"),
  offlineExtensionStatus: () => ipcRenderer.invoke("offline-extension-status"),
  offlineSourceAdd: (input) => ipcRenderer.invoke("offline-source-add", input),
  offlineSourceRemove: (id, deleteItems) => ipcRenderer.invoke("offline-source-remove", id, !!deleteItems),
  offlineSourceUpdate: (id, patch) => ipcRenderer.invoke("offline-source-update", id, patch),
  offlineSettings: (input) => ipcRenderer.invoke("offline-settings", input),
  offlineStorageOpen: () => ipcRenderer.invoke("offline-storage-open"),
  offlineStorageChoose: () => ipcRenderer.invoke("offline-storage-choose"),
  offlineItemUpdate: (id, patch) => ipcRenderer.invoke("offline-item-update", id, patch),
  offlineItemRemove: (id) => ipcRenderer.invoke("offline-item-remove", id),
  offlineHistoryClear: () => ipcRenderer.invoke("offline-history-clear"),
  offlineItemRestore: (token) => ipcRenderer.invoke("offline-item-restore", token),
  offlineRefresh: (sourceId) => ipcRenderer.invoke("offline-refresh", sourceId || ""),
  offlineMedia: (ref) => ipcRenderer.invoke("offline-media", ref),
  offlineCaptureOpen: (ref) => ipcRenderer.invoke("offline-capture-open", ref),
  onOfflineChanged: (cb) => ipcRenderer.on("offline-feed-changed", (_, data) => cb(data)),

  // dedicated Monitoring Mode
  monitoringLoad: () => ipcRenderer.invoke("monitoring-load"),
  monitoringAdd: (input) => ipcRenderer.invoke("monitoring-add", input),
  monitoringRemove: (id) => ipcRenderer.invoke("monitoring-remove", id),
  monitoringMonitorUpdate: (id, patch) => ipcRenderer.invoke("monitoring-monitor-update", id, patch),
  monitoringEventUpdate: (id, patch) => ipcRenderer.invoke("monitoring-event-update", id, patch),
  monitoringMarkRead: () => ipcRenderer.invoke("monitoring-mark-read"),
  monitoringSettings: (patch) => ipcRenderer.invoke("monitoring-settings", patch),
  monitoringOutputOpen: () => ipcRenderer.invoke("monitoring-output-open"),
  monitoringOutputChoose: () => ipcRenderer.invoke("monitoring-output-choose"),
  monitoringRefresh: (id) => ipcRenderer.invoke("monitoring-refresh", id || ""),
  monitoringMedia: (ref) => ipcRenderer.invoke("monitoring-media", ref),
  monitoringPostDetail: (id) => ipcRenderer.invoke("monitoring-post-detail", id),
  monitoringDownload: (id, index) => ipcRenderer.invoke("monitoring-download", id, index),
  monitoringDownloadAll: (id) => ipcRenderer.invoke("monitoring-download-all", id),
  monitoringArtistDetail: (id) => ipcRenderer.invoke("monitoring-artist-detail", id),
  monitoringArtistPostDetail: (monitorId, postId) => ipcRenderer.invoke("monitoring-artist-post-detail", monitorId, postId),
  monitoringArtistDownload: (monitorId, postId, index) => ipcRenderer.invoke("monitoring-artist-download", monitorId, postId, index),
  monitoringArtistPostDownloadAll: (monitorId, postId) => ipcRenderer.invoke("monitoring-artist-post-download-all", monitorId, postId),
  monitoringArtistDownloadAll: (monitorId, fromDate, toDate) => ipcRenderer.invoke("monitoring-artist-download-all", monitorId, fromDate || "", toDate || ""),
  onMonitoringDownloadProgress: (cb) => ipcRenderer.on("monitoring-download-progress", (_, data) => cb(data)),
  onMonitoringChanged: (cb) => ipcRenderer.on("monitoring-changed", (_, data) => cb(data)),
  onMonitoringOpenEvent: (cb) => ipcRenderer.on("monitoring-open-event", (_, id) => cb(id)),

  // screenshot library
  shotsScan: (roots) => ipcRenderer.invoke("shots-scan", roots),
  shotsDefaults: () => ipcRenderer.invoke("shots-defaults"),
  shotsPickFolder: () => ipcRenderer.invoke("shots-pick-folder"),
  shotsThumb: (p) => ipcRenderer.invoke("shots-thumb", p),
  shotsRead: (p) => ipcRenderer.invoke("shots-read", p),
  shotsReveal: (p) => ipcRenderer.invoke("shots-reveal", p),
  shotsLookup: (p) => ipcRenderer.invoke("shots-lookup", p),
  shotsOpen: (p) => ipcRenderer.invoke("shots-open", p),
  shotsCopy: (p) => ipcRenderer.invoke("shots-copy", p),

  killArm: (mins) => ipcRenderer.invoke("kill-arm", mins),
  killCancel: () => ipcRenderer.invoke("kill-cancel"),
  killToggle: (mins) => ipcRenderer.invoke("kill-toggle", mins),
  killStatus: () => ipcRenderer.invoke("kill-status"),
  killAsk: () => ipcRenderer.send("kill-ask"),
  onKillStatus: (cb) => ipcRenderer.on("kill-status", (_, s) => cb(s)),
  onKillAsk: (cb) => ipcRenderer.on("kill-ask", () => cb())
});
