"use strict";

const { app, BrowserWindow, ipcMain } = require("electron");
const fs = require("fs");
const path = require("path");

app.disableHardwareAcceleration();
app.commandLine.appendSwitch("disable-features","WinUseBrowserSpellChecker");
const smokeRoot=path.join(__dirname,"..","dist-verify","ui-smoke-data");
fs.mkdirSync(smokeRoot,{recursive:true});
process.chdir(smokeRoot);
app.setPath("appData",smokeRoot);
app.setPath("userData",path.join(smokeRoot,"user-data"));
app.setPath("sessionData",path.join(smokeRoot,"session"));

let savedState=null,ideaImageCopied="";
ipcMain.handle("store-load",()=>null);
ipcMain.handle("store-security",()=>"permissions-only");
ipcMain.handle("store-save",(_event,data)=>{savedState=data;return true;});
ipcMain.handle("idea-images-pick",()=>({ok:true,items:[{name:"second-smoke.png",file:"b".repeat(64)+".png"}]}));
ipcMain.handle("idea-images-import",()=>({ok:true,items:[{name:"settings-smoke.png",file:"a".repeat(64)+".png"}]}));
ipcMain.handle("idea-image-copy",(_event,name)=>{ideaImageCopied=name;return true;});
ipcMain.handle("app-version",()=>"0.0.0-test");
ipcMain.handle("kill-status",()=>({armed:false,at:0}));
ipcMain.handle("pet-recents",()=>[]);
ipcMain.handle("update-check",()=>({ok:true,available:false,current:"0.0.0-test",latest:"0.0.0-test"}));
ipcMain.handle("hotkey-toggle",(_event,enabled)=>({ok:true,enabled:!!enabled,combo:"Ctrl+Alt+P"}));
ipcMain.handle("hotkeys-update",(_event,hotkeys)=>({ok:true,registered:true,hotkeys}));
ipcMain.on("hotkey-capture",()=>{});
ipcMain.handle("media-assets",()=>({}));
const offlineMediaRefs=["d","e","f"].map((value)=>"media/"+value.repeat(64)+".png");
const offlineVideoRef="media/"+"7".repeat(64)+".mp4";
const offlineAvatarRef="media/"+"8".repeat(64)+".png",offlineCommentImageRef="media/"+"9".repeat(64)+".png";
const offlineFixture={settings:{retentionDays:30,maxItems:2000,historyCleanupMode:"manual",historyRetentionHours:24,historyStorageMB:1024,freshnessDays:3,feedLayout:"cards"},sources:[],items:[{id:"offline-smoke",sourceKey:"capture:smoke",sourceId:"",platform:"reddit",community:"r/SmokeTest",title:"Saved Reddit post",author:"smoke_author",authorFlair:"Helpful human",postFlair:"Datamined",authorAvatar:offlineAvatarRef,content:"The captured post body stays readable offline.",contentBlocks:[{type:"heading",level:1,runs:[{text:"Readable heading",bold:true}]},{type:"paragraph",runs:[{text:"The captured post body stays ",bold:false},{text:"readable offline.",bold:true}]},{type:"listItem",ordered:false,index:1,depth:0,runs:[{text:"First saved point",bold:false}]}],date:Date.now(),downloadedAt:Date.now(),updatedAt:Date.now(),read:false,readAt:0,favorite:false,score:700,commentCount:90,comments:[{author:"commenter",avatar:offlineAvatarRef,body:"A captured comment.",contentBlocks:[{type:"quote",runs:[{text:"A captured quote."}]}],media:[offlineCommentImageRef],score:6,depth:0,date:Date.now()},{author:"reply",avatar:offlineAvatarRef,body:"A nested reply.",media:[offlineVideoRef],gifMedia:[offlineVideoRef],score:2,depth:1,date:Date.now()}],media:offlineMediaRefs.concat([offlineVideoRef]),mediaUrls:[],captureRef:"captures/"+"a".repeat(64)+".mhtml",captureMime:"multipart/related",captureSize:6400}],updatedAt:Date.now(),storagePath:"C:\\Sinrad Offline",storage:{bytes:6400,files:6},sync:{active:false,queued:false}};
offlineFixture.items=Array.from({length:20},(_,index)=>({id:"offline-filler-"+index,sourceKey:"capture:filler-"+index,sourceId:"",platform:"web",community:"Saved page",title:"Offline filler "+index,author:"",content:"Keeps the smoke list tall enough to verify stable navigation.",date:Date.now()-index,downloadedAt:Date.now(),updatedAt:Date.now(),read:false,readAt:0,favorite:false,score:0,commentCount:0,comments:[],media:[],mediaUrls:[],captureRef:"",captureMime:"",captureSize:100})).slice(0,12).concat(offlineFixture.items,Array.from({length:8},(_,index)=>({id:"offline-filler-after-"+index,sourceKey:"capture:filler-after-"+index,sourceId:"",platform:"web",community:"Saved page",title:"Offline filler after "+index,author:"",content:"Keeps the smoke list tall enough to verify stable navigation.",date:Date.now()-100-index,downloadedAt:Date.now(),updatedAt:Date.now(),read:false,readAt:0,favorite:false,score:0,commentCount:0,comments:[],media:[],mediaUrls:[],captureRef:"",captureMime:"",captureSize:100})));
ipcMain.handle("offline-load",()=>offlineFixture);
ipcMain.handle("offline-storage-open",()=>true);
ipcMain.handle("offline-storage-choose",()=>({ok:false,canceled:true}));
ipcMain.handle("offline-extension-status",()=>({connected:true,lastSeen:Date.now(),version:"1.3.3",method:"browser-extension"}));
ipcMain.handle("offline-source-add",(_event,input)=>{const handle=String(input&&input.handle||"").replace(/^r\//i,"");const source={id:"source-"+handle.toLowerCase(),platform:"reddit",adapter:"extension",handle,label:"r/"+handle,sort:"new",limit:30,intervalHours:24,topComments:0,lastSync:0,syncRequestedAt:Date.now(),lastError:""};offlineFixture.sources.push(source);return {ok:true,source};});
ipcMain.handle("offline-media",()=>"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=");
ipcMain.handle("offline-settings",(_event,patch)=>{Object.assign(offlineFixture.settings,patch||{});return offlineFixture;});
ipcMain.handle("offline-item-update",(_event,id,patch)=>{const item=offlineFixture.items.find((entry)=>entry.id===id);if(item){Object.assign(item,patch||{});item.readAt=item.read?(item.readAt||Date.now()):0;}return item||null;});
ipcMain.handle("offline-item-remove",()=>({ok:true,undoToken:"offline-smoke-undo"}));
ipcMain.handle("offline-history-clear",()=>({ok:true,removed:0,undoToken:""}));
ipcMain.handle("offline-item-restore",()=>({ok:true,restored:1}));
ipcMain.handle("offline-source-update",()=>offlineFixture.sources[0]||null);
const monitoringFixture={settings:{notifications:true,defaultIntervalMinutes:1440,retentionDays:90,maxEvents:2000,downloadFolder:"C:\\Users\\Smoke\\Downloads"},monitors:[{id:"monitor-smoke",kind:"pawchive",label:"Smoke Creator",url:"https://pawchive.pw/patreon/user/1",enabled:true,initialized:true,intervalMinutes:1440,lastChecked:Date.now(),avatarRef:"media/"+"a".repeat(64)+".png",bannerRef:"media/"+"b".repeat(64)+".png"}],events:[{id:"event-smoke",monitorId:"monitor-smoke",kind:"pawchive",title:"New illustrated post",summary:"Preview card smoke test",date:Date.now(),discoveredAt:Date.now(),read:false,url:"https://pawchive.pw/patreon/user/1/post/2",mediaRef:"media/"+"c".repeat(64)+".png"},{id:"event-older",monitorId:"monitor-smoke",kind:"pawchive",title:"Older illustrated post",summary:"Neighbor navigation smoke test",date:Date.now()-86400000,discoveredAt:Date.now()-86400000,read:true,url:"https://pawchive.pw/patreon/user/1/post/1",mediaRef:"media/"+"c".repeat(64)+".png"}],updatedAt:Date.now()};
ipcMain.handle("monitoring-load",()=>monitoringFixture);
ipcMain.handle("monitoring-output-open",()=>true);
ipcMain.handle("monitoring-output-choose",()=>({ok:false,canceled:true}));
ipcMain.handle("monitoring-media",()=>"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=");
ipcMain.handle("monitoring-event-update",()=>monitoringFixture.events[0]);
ipcMain.handle("monitoring-monitor-update",(_event,id,patch)=>{const monitor=monitoringFixture.monitors.find((entry)=>entry.id===id);if(monitor)Object.assign(monitor,patch||{});return monitor||null;});
ipcMain.handle("monitoring-post-detail",(_event,id)=>({ok:true,detail:{eventId:id,monitorId:"monitor-smoke",creator:"Smoke Creator",originalUrl:"https://pawchive.pw/patreon/user/1/post/"+(id==="event-older"?"1":"2"),title:id==="event-older"?"Older illustrated post":"New illustrated post",author:"Smoke Creator",content:"Reader smoke test",date:id==="event-older"?Date.now()-86400000:Date.now(),files:[{name:"smoke.png",kind:"image",path:"/aa/bb/"+"c".repeat(64)+".png",src:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="},{name:"smoke.mp4",kind:"video",path:"/dd/ee/"+"d".repeat(64)+".mp4",src:"sinrad-monitor://file/dd/ee/"+"d".repeat(64)+".mp4"}]}}));
ipcMain.handle("monitoring-artist-detail",()=>({ok:true,artist:{monitorId:"monitor-smoke",label:"Smoke Creator",url:"https://pawchive.pw/patreon/user/1",service:"patreon",avatarRef:"media/"+"a".repeat(64)+".png",bannerRef:"media/"+"b".repeat(64)+".png",intervalMinutes:1440,enabled:true,posts:[{postId:"2",title:"New illustrated post",summary:"Artist library smoke test",date:Date.now(),attachmentCount:2,previewSrc:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="},{postId:"1",title:"Older illustrated post",summary:"Older work",date:new Date('2021-06-15T12:00:00Z').getTime(),attachmentCount:1,previewSrc:""}]}}));
ipcMain.handle("monitoring-artist-post-detail",()=>({ok:true,detail:{monitorId:"monitor-smoke",postId:"2",creator:"Smoke Creator",originalUrl:"https://pawchive.pw/patreon/user/1/post/2",title:"Artist work",author:"Smoke Creator",content:"Opened from the artist library",date:Date.now(),files:[{name:"archive.zip",kind:"file",path:"/aa/bb/"+"e".repeat(64)+".zip",src:""}]}}));
ipcMain.handle("monitoring-artist-download",()=>({ok:false,canceled:true}));
ipcMain.handle("monitoring-artist-post-download-all",()=>({ok:false,canceled:true}));
ipcMain.handle("monitoring-artist-download-all",(event)=>{event.sender.send("monitoring-download-progress",{id:"smoke-download",status:"active",label:"Smoke Creator",done:0,total:1,files:0,failed:0,queued:0});event.sender.send("monitoring-download-progress",{id:"smoke-download",status:"done",label:"Smoke Creator",done:1,total:1,files:1,failed:0,queued:0});return {ok:true,count:1,postCount:1,failed:0};});
const previewFixture={data:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",kind:"rich"};
ipcMain.handle("site-preview",()=>previewFixture);
ipcMain.handle("folder-preview",()=>previewFixture.data);

async function run(){
  const win=new BrowserWindow({show:false,width:process.env.SINRAD_UI_SCREENSHOT?1440:800,height:process.env.SINRAD_UI_SCREENSHOT?900:600,webPreferences:{preload:path.join(__dirname,"..","preload.js"),contextIsolation:true,nodeIntegration:false,sandbox:true,webSecurity:true,backgroundThrottling:false,offscreen:!!process.env.SINRAD_UI_SCREENSHOT}});
  win.webContents.session.setSpellCheckerEnabled(false);
  await win.loadFile(path.join(__dirname,"..","index.html"));
  const result=await win.webContents.executeJavaScript(`(async function(){try{
    const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
    const waitFor=async selector=>{for(let i=0;i<100;i++){const el=document.querySelector(selector);if(el)return el;await pause(25);}throw new Error("Missing "+selector);};
    const click=selector=>{const el=document.querySelector(selector);if(!el)throw new Error("Missing "+selector);el.click();};
    const forcePreview=async selector=>{const image=document.querySelector(selector);if(image&&typeof _previewLoad==='function')_previewLoad(image);await pause(40);};
    await waitFor('[data-nav="links"]');
    click('[data-nav="links"]');await pause(30);
    document.querySelector('#lk_url').value='https://example.test/smoke-link';
    click('[data-action="link-add"]');await pause(80);
    await forcePreview('.link-preview .module-preview-img');
    const link=Array.from(document.querySelectorAll('.link-card .lc-title')).some(el=>el.textContent.includes('example.test'));
    const linkPreview=!!document.querySelector('.link-preview .module-preview-img[src^="data:image"]');
    click('[data-nav="folders"]');await pause(30);
    document.querySelector('#fd_path').value='C:\\\\Sinrad-Smoke-Test';
    click('[data-action="folder-add"]');await pause(80);
    await forcePreview('.folder-preview .module-preview-img');
    const folder=Array.from(document.querySelectorAll('.folder-row .fr-path')).some(el=>el.textContent.includes('Sinrad-Smoke-Test'));
    const folderPreview=!!document.querySelector('.folder-preview .module-preview-img[src^="data:image"]');
    click('[data-nav="vault"]');await pause(30);
    click('[data-action="vault-new"]');await pause(30);
    document.querySelector('#v_name').value='Sinrad Smoke Entry';
    document.querySelector('#v_url').value='https://example.test/login';
    click('#modal-confirm');await pause(80);
    await forcePreview('.vault-preview .module-preview-img');
    const vault=Array.from(document.querySelectorAll('.card h3')).some(el=>el.textContent==='Sinrad Smoke Entry');
    const vaultPreview=!!document.querySelector('.vault-preview .module-preview-img[src^="data:image"]');
    click('[data-nav="ideas"]');await pause(30);
    ideaImportMedia=[{name:'settings-smoke.png',file:'a'.repeat(64)+'.png'}];renderView();
    const importBox=document.querySelector('#idea_import_text');
    importBox.value='SINRAD_IDEAS_V1\\n\\nIDEA\\nTITLE: Make the settings spacing shorter\\nTYPE: quick change\\nDETAILS: Keep the controls easy to scan.\\nREFERENCES: settings-smoke.png';
    importBox.dispatchEvent(new Event('input',{bubbles:true}));click('[data-action="idea-import-check"]');await pause(30);
    const ideaImportPreview=!!document.querySelector('.idea-import-card')&&document.querySelector('.idea-import-card').textContent.includes('Make the settings spacing shorter'),ideaImportImage=!!document.querySelector('.idea-import-media img[src^="sinrad-idea://media/"]');
    click('[data-action="idea-import-add"]');await pause(80);
    const ideaCard=document.querySelector('.idea-list-card'),ideasModule=ideaImportPreview&&ideaImportImage&&!!ideaCard&&ideaCard.textContent.includes('Make the settings spacing shorter')&&ideaCard.textContent.includes('Quick change')&&state.ideas[0].attachments.length===1;
    click('[data-action="idea-open"]');await pause(30);
    const ideaReader=!!document.querySelector('.idea-reader')&&document.querySelector('.idea-reader').textContent.includes('Keep the controls easy to scan.')&&!!document.querySelector('[data-action="idea-back"]');
    document.querySelector('.idea-reader-media figure').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:120,clientY:120}));await pause(20);
    const ideaImageMenu=Array.from(document.querySelectorAll('#ctxmenu .ci-label')).some(el=>el.textContent==='Copy image');click('#ctxmenu [data-action="idea-image-copy"]');await pause(20);
    click('[data-action="idea-back"]');await pause(20);
    document.querySelector('.idea-list-card').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:120,clientY:120}));await pause(20);
    const ideaMenuLabels=Array.from(document.querySelectorAll('#ctxmenu .ci-label')).map(el=>el.textContent),ideaContextMenu=['Edit idea','Copy for Codex','In Progress','Testing','Done','Delete idea'].every(label=>ideaMenuLabels.includes(label));
    click('#ctxmenu [data-action="idea-edit"]');await pause(20);click('[data-action="idea-edit-images-pick"]');await pause(20);const ideaEditImages=document.querySelectorAll('#idea_edit_media img').length===2;click('#modal-confirm');await pause(50);
    document.querySelector('.idea-list-card').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:120,clientY:120}));await pause(20);
    click('#ctxmenu [data-action="idea-status"][data-status="ready"]');await pause(50);
    click('[data-action="idea-pane"][data-pane="ready"]');await pause(30);
    const ideaStatusChanged=!!document.querySelector('.idea-list-card.status-ready')&&ideaCodexText(state.ideas[0]).includes('SINRAD IDEA');
    const globalInput=document.querySelector('#globalSearchInput');
    globalInput.value='example.test';globalInput.dispatchEvent(new Event('input',{bubbles:true}));await pause(50);
    const globalSearch=Array.from(document.querySelectorAll('.gs-result .gs-copy b')).some(el=>el.textContent.includes('example.test'));
    click('[data-action="offline-mode"]');await pause(80);
    const offlineMode=document.querySelector('#window').classList.contains('offline-mode')&&!!document.querySelector('.offline-shell')&&getComputedStyle(document.querySelector('.sidebar')).display==='none';
    const offlineGlobalSearch=getComputedStyle(document.querySelector('#globalSearch')).display!=='none'&&!document.querySelector('#globalSearchInput').disabled;
    const offlineTabs=['Unread','History','Favorites'].every(label=>Array.from(document.querySelectorAll('.of-toolbar button')).some(el=>el.textContent===label))&&!Array.from(document.querySelectorAll('.of-toolbar button')).some(el=>el.textContent==='All');
    click('[data-action="offline-layout"][data-layout="scroll"]');await pause(30);
    const offlineScroll=!!document.querySelector('.of-feed.scroll')&&offlineData.settings.feedLayout==='scroll';
    click('[data-action="offline-layout"][data-layout="cards"]');await pause(30);
    offlineData.items.filter(item=>item.id.startsWith('offline-filler')).forEach(item=>{item.community='r/SmokeTest';});renderOfflineView();await pause(160);
    const smokeOfflineCard=document.querySelector('.of-card[data-id="offline-smoke"]'),offlineCard=!!smokeOfflineCard&&!!smokeOfflineCard.querySelector('video.of-media[src^="sinrad-offline://media/"][data-preview-loop="5"]')&&smokeOfflineCard.textContent.includes('The captured post body stays readable offline.')&&smokeOfflineCard.textContent.includes('Popular')&&document.querySelector('.of-storage').textContent.includes('KB');
    document.querySelector('#content').scrollTop=Math.max(0,smokeOfflineCard.offsetTop-180);await pause(30);const offlineReturnOffset=smokeOfflineCard.getBoundingClientRect().top-document.querySelector('#content').getBoundingClientRect().top;
    click('.of-card[data-id="offline-smoke"]');await pause(40);
    const gallery=document.querySelector('.of-gallery'),offlineReader=!!gallery&&gallery.querySelectorAll('.of-gallery-image[src^="data:image"]').length===3&&!!gallery.querySelector('.of-gallery-video[src^="sinrad-offline://media/"]')&&gallery.getBoundingClientRect().height>300&&getComputedStyle(gallery.querySelector('.of-gallery-stage')).borderTopWidth==='1px'&&document.querySelectorAll('.of-comment').length===2&&document.querySelectorAll('.of-avatar[src^="data:image"]').length===3&&!!document.querySelector('.of-comment img.of-comment-media[src^="data:image"]')&&!!document.querySelector('.of-comment video.of-comment-media[src^="sinrad-offline://media/"]')&&!!document.querySelector('.of-comment-body.rich blockquote')&&!!document.querySelector('.of-author-flair')&&document.querySelector('.of-post-flair').textContent==='Datamined'&&!!document.querySelector('.of-body.rich strong')&&!!document.querySelector('.of-rich-li')&&!!document.querySelector('.of-reader>[data-action="offline-item-back"]')&&document.querySelectorAll('.of-reader button').length===3&&document.querySelector('.of-reader').textContent.includes('smoke_author')&&document.querySelector('.of-reader').textContent.includes('The captured post body stays readable offline.')&&getComputedStyle(document.querySelector('.of-article h1')).userSelect==='text';
    click('[data-action="offline-gallery-next"]');await pause(20);
    const offlineGallery=gallery.dataset.galleryIndex==='1'&&gallery.querySelector('[data-gallery-image="1"]').classList.contains('active')&&gallery.querySelector('.of-gallery-count b').textContent==='2';
    document.querySelector('#content').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:window.innerWidth-80,clientY:240}));await pause(20);
    const offlineMenuLabels=Array.from(document.querySelectorAll('#ctxmenu .ci-label')).map(el=>el.textContent),offlineReaderMenuBack=['Back','Add r/SmokeTest to Offline','Mark as unread','Favorite','Open original'].every(label=>offlineMenuLabels.includes(label))&&!offlineMenuLabels.includes('Open saved page');
    offlineExtension.connected=false;offlineExtensionRequiredModal('SmokeTest');await pause(30);
    const offlineConnectionPrompt=document.querySelector('#overlay').classList.contains('show')&&document.querySelector('#modal-title').textContent==='Browser extension not connected'&&document.querySelector('#modal-body').textContent.includes('Connection status')&&document.querySelector('#modal-body').textContent.includes('Not connected');
    click('[data-action="modal-cancel"]');offlineExtension.connected=true;await pause(20);
    document.querySelector('#content').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:window.innerWidth-80,clientY:240}));await pause(20);
    click('#ctxmenu [data-action="offline-source-follow"]');await pause(50);
    const offlineBackgroundSource=offlineData.sources.some(source=>source.label==='r/SmokeTest');
    click('[data-action="offline-item-back"]');await pause(30);
    await pause(140);const returnCard=document.querySelector('.of-card[data-id="offline-filler-after-0"]'),offlineReaderMenuReturned=!document.querySelector('.of-reader')&&!!document.querySelector('.of-feed')&&document.querySelector('#content').scrollTop>0&&!!returnCard&&Math.abs((returnCard.getBoundingClientRect().top-document.querySelector('#content').getBoundingClientRect().top)-offlineReturnOffset)<24;
    click('[data-action="offline-mode"]');await pause(50);
    const normalMode=!document.querySelector('#window').classList.contains('offline-mode')&&getComputedStyle(document.querySelector('.sidebar')).display!=='none';
    click('[data-action="monitoring-mode"]');await pause(80);
    const monitoringMode=document.querySelector('#window').classList.contains('monitoring-mode')&&!!document.querySelector('.monitoring-shell')&&!!document.querySelector('[data-action="monitoring-exit"]')&&getComputedStyle(document.querySelector('.sidebar')).display==='none';
    const monitoringSelectable=getComputedStyle(document.querySelector('.monitoring-shell')).userSelect==='text';
    const monitoringGlobalSearch=getComputedStyle(document.querySelector('#globalSearch')).display!=='none'&&!document.querySelector('#globalSearchInput').disabled;
    const monitoringCard=!!document.querySelector('.mon-event.has-image')&&!!document.querySelector('.mon-event-preview[src^="data:image"]');
    const monitoringReturnTop=Math.min(75,Math.max(0,document.querySelector('#content').scrollHeight-document.querySelector('#content').clientHeight));document.querySelector('#content').scrollTop=monitoringReturnTop;
    click('[data-action="monitoring-event-open"]');await pause(80);
    const reader=document.querySelector('.mon-reader'),readerFile=reader&&reader.querySelector('.mon-file'),readerImage=reader&&reader.querySelector('.mon-reader-media');
    const monitoringReader=!!reader&&!!readerFile&&!!readerImage&&readerImage.src.startsWith('data:image')&&!!reader.querySelector('video[preload="auto"][playsinline]')&&!!reader.querySelector('[data-action="monitoring-post-back"]')&&!!reader.querySelector('[data-action="monitoring-post-artist-open"]')&&reader.querySelectorAll('button').length===2&&getComputedStyle(readerFile).borderTopWidth==='0px'&&readerFile.getBoundingClientRect().width>=reader.getBoundingClientRect().width*.75;
    click('[data-action="monitoring-post-artist-open"]');await pause(80);
    const monitoringReaderArtist=!!document.querySelector('.mon-artist')&&document.querySelector('.mon-artist').textContent.includes('Smoke Creator');
    click('[data-action="monitoring-artist-back"]');await pause(160);click('[data-action="monitoring-event-open"]');await pause(80);
    const readerAgain=document.querySelector('.mon-reader'),readerFileAgain=readerAgain&&readerAgain.querySelector('.mon-file');
    readerFileAgain.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:80,clientY:80}));await pause(20);
    const monitoringReaderLabels=Array.from(document.querySelectorAll('#ctxmenu .ci-label')).map(el=>el.textContent),monitoringReaderMenu=monitoringReaderLabels.includes('Download image')&&monitoringReaderLabels.includes('Back')&&monitoringReaderLabels.includes('Next post');
    click('#ctxmenu [data-action="monitoring-post-nav"][data-id="next"]');await pause(80);
    const monitoringReaderNavigation=!!document.querySelector('.mon-reader')&&document.querySelector('.mon-reader').textContent.includes('Older illustrated post');
    document.querySelector('.mon-file').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:80,clientY:80}));await pause(20);
    click('#ctxmenu [data-action="monitoring-post-back"]');await pause(160);
    const monitoringReaderContextBack=!document.querySelector('.mon-reader')&&!!document.querySelector('.mon-events')&&Math.abs(document.querySelector('#content').scrollTop-monitoringReturnTop)<3;
    click('[data-action="monitoring-event-open"]');await pause(80);
    document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await pause(40);
    const monitoringReaderEscape=!document.querySelector('.mon-reader')&&!!document.querySelector('.mon-events');
    click('[data-action="monitoring-event-open"]');await pause(80);
    click('[data-action="monitoring-post-back"]');await pause(40);
    const monitoringReaderButtonBack=!document.querySelector('.mon-reader')&&!!document.querySelector('.mon-events')&&document.querySelector('#window').classList.contains('monitoring-mode');
    click('[data-action="monitoring-tab"][data-tab="watchlist"]');await pause(60);
    const monitoringProfile=!!document.querySelector('.mon-watch-avatar-img[src^="data:image"]')&&!!document.querySelector('.mon-watch-banner[src^="data:image"]')&&!document.querySelector('[data-action="monitoring-add"]');
    document.querySelector('.mon-watchlist').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:window.innerWidth-80,clientY:window.innerHeight-80}));await pause(20);
    const monitoringWatchlistMenu=Array.from(document.querySelectorAll('#ctxmenu .ci-label')).some(el=>el.textContent==='Add watcher');hideMenu();
    document.querySelector('.mon-watch').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:100,clientY:100}));await pause(20);
    const watchMenuLabels=Array.from(document.querySelectorAll('#ctxmenu .ci-label')).map(el=>el.textContent),monitoringWatchMenu=watchMenuLabels.includes('Edit check time')&&watchMenuLabels.includes('Open artist');
    click('#ctxmenu [data-action="monitoring-monitor-interval"]');await pause(20);
    document.querySelector('#mon_edit_interval').value='60';click('#modal-confirm');await pause(70);
    const monitoringIntervalEdited=!!document.querySelector('.mon-watch-meta')&&document.querySelector('.mon-watch-meta').textContent.includes('Every 1h');
    click('[data-action="monitoring-monitor-open"]');await pause(80);
    const monitoringArtist=!!document.querySelector('.mon-artist')&&!!document.querySelector('.mon-artist-grid .mon-artist-post')&&document.querySelector('.mon-artist').textContent.includes('Smoke Creator');
    const monitoringDateRange=document.querySelectorAll('[data-action="monitoring-artist-date-open"]').length===2&&!document.querySelector('.mon-artist-range input, .mon-artist-range select')&&!!document.querySelector('[data-action="monitoring-artist-download-range"]');
    click('[data-action="monitoring-artist-date-open"][data-side="from"]');await pause(15);const hasEarliest=document.querySelector('[data-action="monitoring-artist-date-edge"]').textContent==='Earliest';click('[data-action="monitoring-artist-date-edge"]');await pause(15);
    click('[data-action="monitoring-artist-date-open"][data-side="to"]');await pause(15);const hasLatest=document.querySelector('[data-action="monitoring-artist-date-edge"]').textContent==='Latest';click('[data-action="monitoring-artist-date-edge"]');await pause(15);
    const monitoringDateEdges=hasEarliest&&hasLatest&&document.querySelectorAll('.mon-artist-post').length===2;
    click('[data-action="monitoring-artist-date-open"][data-side="from"]');await pause(20);
    const pickerYears=document.querySelectorAll('[data-action="monitoring-artist-date-year"]'),pickerYearOnlyPosts=pickerYears.length===2;
    click('[data-action="monitoring-artist-date-year"]');await pause(20);
    const pickerMonthOnlyPosts=document.querySelectorAll('[data-action="monitoring-artist-date-month"]').length===1;
    click('[data-action="monitoring-artist-date-month"]');await pause(20);
    const pickerDateOnlyPosts=document.querySelectorAll('[data-action="monitoring-artist-date-pick"]').length===1;
    click('[data-action="monitoring-artist-date-pick"]');await pause(25);
    const monitoringDateFilter=document.querySelectorAll('.mon-artist-post').length===1&&document.querySelector('.mon-range-title').textContent.includes('1 of 2 shown')&&pickerYearOnlyPosts&&pickerMonthOnlyPosts&&pickerDateOnlyPosts;
    click('[data-action="monitoring-artist-range-reset"]');await pause(25);
    click('[data-action="monitoring-artist-download-range"]');await pause(20);click('#modal-confirm');await pause(50);
    const monitoringRangeDownload=Array.from(document.querySelectorAll('.toast')).some(el=>el.textContent.includes('Downloaded 1 files from 1 works'));
    const monitoringDownloadStatus=document.querySelector('#monitorDownloadStatus').classList.contains('show')&&document.querySelector('#monitorDownloadStatus').classList.contains('done')&&document.querySelector('#monitorDownloadText').textContent.includes('1 saved');
    document.querySelector('.mon-artist').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:110,clientY:110}));await pause(20);
    const artistMenuLabels=Array.from(document.querySelectorAll('#ctxmenu .ci-label')).map(el=>el.textContent),monitoringArtistMenu=artistMenuLabels.includes('Download everything')&&artistMenuLabels.includes('Edit check time')&&artistMenuLabels.includes('Back');
    click('#ctxmenu [data-action="monitoring-artist-back"]');await pause(30);
    const monitoringArtistMenuBack=!document.querySelector('.mon-artist')&&!!document.querySelector('.mon-watch-list');
    click('[data-action="monitoring-monitor-open"]');await pause(60);click('[data-action="monitoring-artist-post-open"]');await pause(70);
    const monitoringArtistPost=!!document.querySelector('.mon-reader')&&document.querySelector('.mon-reader').textContent.includes('Opened from the artist library');
    const monitoringFileTile=!!document.querySelector('.mon-media-file[data-action="monitoring-download"]')&&document.querySelector('.mon-media-file').textContent.includes('archive.zip')&&!document.querySelector('.mon-media-file').textContent.includes('Right-click to download');
    click('[data-action="monitoring-post-back"]');await pause(30);
    const monitoringArtistPostBack=!!document.querySelector('.mon-artist')&&!!document.querySelector('.mon-artist-post');
    click('[data-action="monitoring-artist-back"]');await pause(30);
    click('[data-action="monitoring-exit"]');await pause(50);
    const monitoringExit=!document.querySelector('#window').classList.contains('monitoring-mode')&&getComputedStyle(document.querySelector('.sidebar')).display!=='none';
    click('[data-action="settings-open"]');await pause(40);
    const settingsOpen=document.querySelector('#settingsPanel').classList.contains('show')&&document.querySelector('#titlebar>#settingsToggle')&&document.querySelectorAll('[data-settings-tab]').length===3&&!document.querySelector('[data-settings-tab="search"]');
    click('[data-settings-tab="parking"]');await pause(30);
    const settingsParking=!!document.querySelector('.settings-section-title')&&!document.querySelector('[data-setting-action^="park"]')&&!document.querySelector('#settingStackMin');
    click('[data-settings-tab="tools"]');await pause(30);
    const toolRow=document.querySelector('[data-settings-menu="offline-storage"]'),monitorOutputRow=document.querySelector('[data-settings-menu="monitoring-output"]'),hotkeyBox=document.querySelector('[data-hotkey-field="globalSearch"]');
    const settingsTools=!!document.querySelector('[data-settings-menu="extension"]')&&!!toolRow&&!!monitorOutputRow&&!document.querySelector('[data-setting-action]')&&toolRow.querySelector('.setting-path').textContent.includes('Sinrad Offline')&&monitorOutputRow.querySelector('.setting-path').textContent.includes('Downloads')&&document.querySelectorAll('[data-hotkey-field]').length===4&&toolRow.getBoundingClientRect().height<42&&hotkeyBox.getBoundingClientRect().height<=28;
    toolRow.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:window.innerWidth-120,clientY:220}));await pause(20);
    const settingsMenuLabels=Array.from(document.querySelectorAll('#ctxmenu .ci-label')).map(el=>el.textContent),settingsContextMenu=['Open folder','Change folder','Back'].every(label=>settingsMenuLabels.includes(label));
    click('#ctxmenu [data-action="settings-offline-change"]');await pause(30);
    const settingsCancelSafe=document.querySelector('#settingsPanel').classList.contains('show')&&document.querySelector('.setting-path').textContent.includes('Sinrad Offline');
    monitorOutputRow.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:window.innerWidth-120,clientY:250}));await pause(20);
    const monitorOutputMenuLabels=Array.from(document.querySelectorAll('#ctxmenu .ci-label')).map(el=>el.textContent),settingsMonitoringOutput=['Open folder','Change folder','Back'].every(label=>monitorOutputMenuLabels.includes(label));
    click('#ctxmenu [data-action="settings-monitoring-output-change"]');await pause(25);
    const settingsMonitoringCancelSafe=document.querySelector('#settingsPanel').classList.contains('show')&&monitorOutputRow.querySelector('.setting-path').textContent.includes('Downloads');
    const hotkeyField=document.querySelector('[data-hotkey-field="globalSearch"]');hotkeyField.focus();hotkeyField.dispatchEvent(new KeyboardEvent('keydown',{key:'G',ctrlKey:true,shiftKey:true,bubbles:true}));await pause(40);
    const hotkeyChanged=hotkeyField.value==='Ctrl + Shift + G'&&document.querySelector('#globalSearch>kbd').textContent==='Ctrl + Shift + G';
    click('[data-action="settings-back"]');await pause(30);
    const settingsClosed=!document.querySelector('#settingsPanel').classList.contains('show');
    const consoleRemoved=!document.querySelector('#consoleDock'),accessibleNav=document.querySelectorAll('#nav button.nav-item').length===6&&!!document.querySelector('#nav button.nav-item[aria-current="page"]');
    document.querySelector('[data-action="command-open"]').click();await pause(20);
    const commandNavigation=['Navigate','Create','Actions'].every(label=>Array.from(document.querySelectorAll('.cp-group')).some(el=>el.textContent===label))&&document.querySelector('#commandInput').placeholder==='Find a page or command…';
    document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
    return {link,linkPreview,folder,folderPreview,vault,vaultPreview,ideasModule,ideaReader,ideaImageMenu,ideaEditImages,ideaContextMenu,ideaStatusChanged,globalSearch,offlineMode,offlineGlobalSearch,offlineTabs,offlineScroll,offlineCard,offlineReader,offlineGallery,offlineReaderMenuBack,offlineConnectionPrompt,offlineBackgroundSource,offlineReaderMenuReturned,normalMode,monitoringMode,monitoringSelectable,monitoringGlobalSearch,monitoringCard,monitoringReader,monitoringReaderArtist,monitoringReaderMenu,monitoringReaderNavigation,monitoringReaderContextBack,monitoringReaderEscape,monitoringReaderButtonBack,monitoringProfile,monitoringWatchlistMenu,monitoringWatchMenu,monitoringIntervalEdited,monitoringArtist,monitoringDateRange,monitoringDateEdges,monitoringDateFilter,monitoringRangeDownload,monitoringDownloadStatus,monitoringArtistMenu,monitoringArtistMenuBack,monitoringArtistPost,monitoringFileTile,monitoringArtistPostBack,monitoringExit,settingsOpen,settingsParking,settingsTools,settingsContextMenu,settingsCancelSafe,settingsMonitoringOutput,settingsMonitoringCancelSafe,hotkeyChanged,settingsClosed,consoleRemoved,accessibleNav,commandNavigation};
  }catch(error){return {__error:String(error&&error.stack||error)};}})()`);
  if(result&&result.__error)throw new Error(result.__error);
  const persisted=!!(savedState&&savedState.links&&savedState.links.length&&savedState.folders&&savedState.folders.length&&savedState.vault&&savedState.vault.length&&savedState.ideas&&savedState.ideas.length);
  if(!result.link||!result.linkPreview||!result.folder||!result.folderPreview||!result.vault||!result.vaultPreview||!result.ideasModule||!result.ideaReader||!result.ideaImageMenu||!result.ideaEditImages||ideaImageCopied!=="a".repeat(64)+".png"||!result.ideaContextMenu||!result.ideaStatusChanged||!result.globalSearch||!result.offlineMode||!result.offlineGlobalSearch||!result.offlineTabs||!result.offlineScroll||!result.offlineCard||!result.offlineReader||!result.offlineGallery||!result.offlineReaderMenuBack||!result.offlineConnectionPrompt||!result.offlineBackgroundSource||!result.offlineReaderMenuReturned||!result.normalMode||!result.monitoringMode||!result.monitoringSelectable||!result.monitoringGlobalSearch||!result.monitoringCard||!result.monitoringReader||!result.monitoringReaderArtist||!result.monitoringReaderMenu||!result.monitoringReaderNavigation||!result.monitoringReaderContextBack||!result.monitoringReaderEscape||!result.monitoringReaderButtonBack||!result.monitoringProfile||!result.monitoringWatchlistMenu||!result.monitoringWatchMenu||!result.monitoringIntervalEdited||!result.monitoringArtist||!result.monitoringDateRange||!result.monitoringDateEdges||!result.monitoringDateFilter||!result.monitoringRangeDownload||!result.monitoringDownloadStatus||!result.monitoringArtistMenu||!result.monitoringArtistMenuBack||!result.monitoringArtistPost||!result.monitoringFileTile||!result.monitoringArtistPostBack||!result.monitoringExit||!result.settingsOpen||!result.settingsParking||!result.settingsTools||!result.settingsContextMenu||!result.settingsCancelSafe||!result.settingsMonitoringOutput||!result.settingsMonitoringCancelSafe||!result.hotkeyChanged||!result.settingsClosed||!result.consoleRemoved||!result.accessibleNav||!result.commandNavigation||!persisted)throw new Error("UI smoke test failed: "+JSON.stringify({result,persisted,ideaImageCopied}));
  if(process.env.SINRAD_UI_SCREENSHOT){
    await win.webContents.executeJavaScript(`offlineMode=false;monitoringMode=false;stopCelebrate();document.querySelectorAll(".toast").forEach(function(item){item.remove();});["overlay","update-modal","commandPalette","settingsPanel"].forEach(function(id){const node=document.getElementById(id);if(node)node.classList.remove("show");});closeGlobalSearch(true);ideaPane="import";ideaImportText="SINRAD_IDEAS_V1\\n\\nIDEA\\nTITLE: Park All misses some tabs\\nTYPE: problem\\nDETAILS: Park All appears to save incomplete batches instead of every open tab.\\nREFERENCES: image-217.png\\n---\\nIDEA\\nTITLE: Click to stop animations\\nTYPE: quick change\\nDETAILS: Allow long app animations to be skipped with one click.\\nREFERENCES: image-217.png\\n---\\nIDEA\\nTITLE: Use each website's real icon\\nTYPE: feature\\nDETAILS: Replace number and placeholder icons with the website favicon.\\nREFERENCES:";ideaImportPreview=parseIdeaImport(ideaImportText);currentView="ideas";document.querySelector("#window").classList.remove("offline-mode","monitoring-mode");renderNav();renderView();`);
    await new Promise(function(resolve){setTimeout(resolve,120);});
    const image=await win.webContents.capturePage();fs.writeFileSync(path.resolve(process.env.SINRAD_UI_SCREENSHOT),image.toPNG());
  }
  console.log("UI smoke test passed:",JSON.stringify(result));
  win.destroy();
}

app.whenReady().then(run).then(()=>app.exit(0)).catch(error=>{console.error(error&&error.stack||error);app.exit(1);});
